version: '3'
services:
  postgres:
    image: "kartoza/postgis"
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=mob
      - POSTGRES_USER=mob
      - POSTGRES_PASSWORD=mob
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
