version: '3'
services:
  postgres:
    image: "kartoza/postgis"
    restart: always
    container_name: "postgis_mobility"
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=mob
      - POSTGRES_USER=mob
      - POSTGRES_PASSWORD=mob
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  mongo:
    image: mongo
    restart: always
    container_name: "mongodb_mobility"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_DATABASE=whirlpool
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  splash:
    image: "scrapinghub/splash"
    restart: always
    container_name: "splash_mobility"
    ports:
      - 5023:5023
      - 8050:8050
      - 8051:8051
