version: '3'
services:
  mongo:
    image: mongo 
    container_name: "carnaval_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_DATABASE=carnaval
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
